backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Home Page"
    file: "index.html"
    fields:
      - { label: "Monthly Title", name: "monthly_title", widget: "string" }
      - { label: "Monthly Message", name: "monthly_message", widget: "text" }
      - { label: "GPS Instagram URL", name: "gps_instagram", widget: "string" }
      - { label: "Pup O'Clock Instagram URL", name: "pup_instagram", widget: "string" }
      - { label: "How It Works", name: "how_it_works", widget: "markdown" }
      - { label: "Prizes", name: "prizes", widget: "markdown" }
      - { label: "Hero Image", name: "hero_image", widget: "image", required: false }
      - { label: "Show Logos", name: "show_logos", widget: "boolean", default: true }
